name: Update App JSON

on:
  schedule:
    - cron: '15 5 * * *'   # Runs daily at 5:15 AM UTC
  workflow_dispatch:       # Allows manual triggering
  push:
    branches:
      - main               # Also runs on push to main

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel --prefer-binary
          python -m pip install .[dev] --timeout 100 --no-cache-dir

      - name: Fetch US State Boundaries
        run: python src/setup/fetch_boundaries.py

      - name: Fetch Congressional Districts
        run: python src/setup/fetch_cd.py

      - name: Fetch Roles
        run: python src/setup/fetch_roles.py

      - name: Fetch States Metadata
        run: python src/setup/fetch_states.py

      - name: Write status.yaml with timestamp
        run: python src/setup/write_status_yaml.py

      - name: Commit and Push if Changes
        run: |
          git config user.name "CI Bot"
          git config user.email "actions@github.com"
          git add docs/status.json
          git add docs/status.yaml
          git add data/**/*.geojson
          git add data/**/*.json
          git diff --quiet && echo "No changes to commit." || (git commit -m "Update agent status [skip ci]" && git push)
